### ISSUE TITLE
`nbconvert-a11y` roadmap

### ISSUE THREAD

**Issue by tonyfast** [deathbeds/nbconvert-a11y#27]
this meta-issue is used to generate issues for roadmap items. each checklist item is converted into an issue to track the progress of each efforts. new roadmap items should be added to this to ensure we have a central place to track progress.

`nbconvert-a11y` intends to be a choke point for accessible developer experiences with open science tools.  in 2024, `nbconvert-a11y` will generate new software, processes, and opportunities that address inaccessibility in open source software.

## user testing

the primary inspiration for continued work on `nbconvert-a11y` is the feedback from affected blind or visually impaired testers. hearing and understanding their experiences is the only way we've been able to develop candidates for assistive technology experiences.

- [ ] BVI user testing for site/notebook navigation
- [ ] BVI user testing for consuming cell inputs
- [ ] BVI user testing for consuming cell outputs
- [ ] user testing of the flexible settings configuration

## automated testing

- [x]  `pytest-axe` automated accessibility testing with deque axe
- [x]  `pytest-w3c` automated accessibility testing with w3c nu validator
- [ ] automated screen reader testing with [guidepup.dev](https://www.guidepup.dev/)
- [ ] automated screen reader and accessibility testing with robot framework
- [ ] `pytest-equal-access` automated accessibility testing with IBM equal access
- [ ] automated accessibility testing with chrome extensions (eg WAVE) in playwright.

## third party testing

we need to test and track third party accessibility violations of upstream libraries. these libraries can be patched by `nbconvert-a11y` or track upstream changes. the efforts are a new contribution model where community members are encouraged to contribute tests verifying inaccessibility. `nbconvert-a11y` can provide a central authority for accessibility efforts rather than diffuse upstream efforts.

- [x] pygments
- [x] ipywidgets
- [ ] `pytest-html`
- [x] flask dev mode
- [ ] pandas
- [ ] matplotlib
- [ ] ipython

## packaging

`nbconvert-a11y` will incubate integrations and extensions to third party software. initially, the requirements to use these tools (eg pytest extensions) are optional dependencies. eventually, they should be moved to their own smaller projects with less entropy.

- [ ] create a standalone `pytest-axe` package
- [ ] create a standalone `pytest-w3c` package
- [ ] create a mkdocs extensions
- [ ] ~~create a sphinx extensions~~ _`nbconvert-a11y` is not readily compatible with sphinx._

## developer experience

- [ ] [containers.dev](https://containers.dev/) integration for better developer experiences, collaboration, and events.
- [ ] a community calendar to manage meetings
- [ ] screen reader workshops to improve literacy among our developers.
- [ ] an in person event
